baseURL = 'http://dbk.wtf/'
languageCode = 'en-us'
title = "dbk's blog"
theme = 'smol'

# Parameters

[params]

  subtitle = "Death by Knowledge... if anything"
  dateFmt = "02.01.2006 15:04"


# Header

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1


# Footer

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/deathbyknowledge"
    weight = 1

  [[menu.footer]]
    name = "Mastodon"
    url = "https://infosec.exchange/@deathbyknowledge"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
